In [2]:
import pandas as pd
import numpy as np
import random
from sklearn.metrics.pairwise import euclidean_distances
from functools import reduce
dataframe = None

# Configurando a base: Ecoli

In [3]:
dataframe = pd.read_csv("databases/ecoli.csv", header=None)
last_row = len(dataframe.columns) - 1
classes = dataframe[last_row]
dataframe = dataframe.drop(columns=[0, last_row])

print(classes)
dataframe

0      cp
1      cp
2      cp
3      cp
4      cp
       ..
331    pp
332    pp
333    pp
334    pp
335    pp
Name: 8, Length: 336, dtype: object


1     2     3    4     5     6     7
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35
..    ...   ...   ...  ...   ...   ...   ...
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52

[336 rows x 7 columns]

# The ANT IS ALgorithm

## The Algortim Paramaters

In [4]:

initial_pheromone = 1
Q = 1
evaporation_rate = 0.1
num_ants = len(dataframe.index)

## Intializintg varaibles

In [5]:
num_instances = len(dataframe.index)
num_instances

336

In [6]:
distance_matrix = euclidean_distances(dataframe)
print(f"Shape: {distance_matrix.shape}")
distance_matrix

Shape: (336, 336)


array([[0.        , 0.45727453, 0.22561028, ..., 0.38509739, 0.40595566,
        0.66370174],
       [0.45727453, 0.        , 0.49335586, ..., 0.58889727, 0.58197938,
        0.81006173],
       [0.22561028, 0.49335586, 0.        , ..., 0.22759613, 0.24596748,
        0.45782093],
       ...,
       [0.38509739, 0.58889727, 0.22759613, ..., 0.        , 0.04358899,
        0.30430248],
       [0.40595566, 0.58197938, 0.24596748, ..., 0.04358899, 0.        ,
        0.29342802],
       [0.66370174, 0.81006173, 0.45782093, ..., 0.30430248, 0.29342802,
        0.        ]])

In [7]:
pheromone_matrix = np.full((num_instances, num_instances), initial_pheromone)
print(f"Shape: {pheromone_matrix.shape}")
pheromone_matrix

Shape: (336, 336)


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [8]:
visibility_matrix = np.zeros((num_instances, num_instances))
for i in range(num_instances):
    for j in range(num_instances):
        if i != j:
            visibility_matrix[i, j] = 1 / distance_matrix[i, j]

print(f"Shape: {visibility_matrix.shape}")
visibility_matrix

Shape: (336, 336)


array([[ 0.        ,  2.18687008,  4.43242207, ...,  2.59674572,
         2.4633232 ,  1.50670089],
       [ 2.18687008,  0.        ,  2.02693449, ...,  1.69808903,
         1.71827393,  1.23447383],
       [ 4.43242207,  2.02693449,  0.        , ...,  4.39374775,
         4.06557814,  2.18426014],
       ...,
       [ 2.59674572,  1.69808903,  4.39374775, ...,  0.        ,
        22.94157339,  3.2862039 ],
       [ 2.4633232 ,  1.71827393,  4.06557814, ..., 22.94157339,
         0.        ,  3.40799088],
       [ 1.50670089,  1.23447383,  2.18426014, ...,  3.2862039 ,
         3.40799088,  0.        ]])

In [9]:
the_colony = np.full((num_ants, num_ants), -1)
last_ants_positions = []
for i in range(num_instances):
    the_colony[i,i] = 1
    last_ants_positions.append(i)

print("The Colony")
print(f"Shape: {the_colony.shape}")
print(the_colony)
print("Last ants positions")
print(f"Shape: {len(last_ants_positions)}")
print(last_ants_positions)

The Colony
Shape: (336, 336)
[[ 1 -1 -1 ... -1 -1 -1]
 [-1  1 -1 ... -1 -1 -1]
 [-1 -1  1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ...  1 -1 -1]
 [-1 -1 -1 ... -1  1 -1]
 [-1 -1 -1 ... -1 -1  1]]
Last ants positions
Shape: 336
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178

## Defening algorihm functions

In [10]:
def get_probalites_array(ant, last_position):
    probs = np.zeros((num_instances, 2))
    not_visted = [ instance 
        for instance in range(num_instances) if the_colony[ant, instance] == -1]

    pheromones = pheromone_matrix[last_position, not_visted]
    visibilities = visibility_matrix[last_position, not_visted]
    trail_smells = np.sum(pheromones * visibilities)
    # print(len(not_visted))
    # print(visibilities.shape)
    # print(pheromones.shape)
    
    # Create probs array keeping the instance index
    for instance in not_visted:
        probs[instance, 0] = instance
        path_smell = \
            pheromone_matrix[last_position, instance] * visibility_matrix[last_position, instance]
        
        probs[instance, 1] = path_smell / trail_smells
    
    return probs


# result = get_probalites_array(0, 0)
# print(result.shape)
# result = result[result[:, 1].argsort()][::-1]
# result = pd.DataFrame(result, columns=['index', 'probalites'])
# print(result)
# print(f"Max value: {result['probalites'].max() * 100}")


In [11]:
def choose_next_path(ant):
    probs = get_probalites_array(ant, last_ants_positions[ant])
    probs = probs[probs[:, 1].argsort()][::-1]

    for ant_choice in range(probs.shape[0]):
        new_instance = int(probs[ant_choice, 0])
        prob = probs[ant_choice, 1]
        fprob = prob * random.randint(0,1)
        if fprob != 0:
            the_colony[ant, new_instance] = 1
            last_ants_positions[ant] = new_instance
            break
        else:
            the_colony[ant, new_instance] = 0
    
    return last_ants_positions[ant]

# choose_next_path(0)

    

In [12]:
def get_path_done(tour):
    if len(tour) <= 1:
        return []
    else:
        return [(tour[i], tour[i + 1]) for i in range(len(tour) - 1)]

def get_tour_length(tour):
    if len(tour) <= 1:
        return 0
    
    tour_length = 0
    for i in range(len(tour) - 1):
        tour_length += distance_matrix[tour[i], tour[i + 1]]

    return tour_length

def update_pheromones():
    pheromones_deposited = np.zeros((num_instances, num_instances))
    for ant in range(the_colony.shape[0]):
        tour = [
            instance for instance in range(num_instances) if the_colony[ant, instance] != -1]

        path_done = get_path_done(tour)
        tour_length = get_tour_length(tour)
        
        for path in path_done:
            pheromones_deposited[path[0], path[1]] += Q / tour_length

    
    for i in range(pheromone_matrix.shape[0]):
        for j in range(pheromone_matrix.shape[1]):
            pheromone_matrix[i, j] = \
            (1 - evaporation_rate) * pheromone_matrix[i,j] + pheromones_deposited[i, j] 

    
# update_pheromones()
    



In [13]:
def run_colony():
    while -1 in the_colony:
        for ant in range(num_instances):
            choose_next_path(ant)
    
        update_pheromones()

run_colony()
the_colony

C:\Users\Reaborn\AppData\Local\Temp/ipykernel_5128/3903684660.py:19: RuntimeWarning: invalid value encountered in double_scalars
  probs[instance, 1] = path_smell / trail_smells


In [ ]:
final = pd.DataFrame(the_colony)
final.to_csv('teste.csv')